# Generated by Django 4.2.7 on 2023-12-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account_number',
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
    ]
