# Generated by Django 4.2.7 on 2023-12-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_customer_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account_balance',
            field=models.FloatField(default=0),
        ),
    ]
