# Generated by Django 4.2.7 on 2023-12-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_transfers'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfers',
            name='amount',
            field=models.CharField(default='amount', max_length=20),
        ),
    ]
