# Generated by Django 4.2.7 on 2023-12-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_transfers_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfers',
            name='amount',
            field=models.CharField(max_length=20),
        ),
    ]
