# Generated by Django 4.2.7 on 2023-12-16 05:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_alter_transfers_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfers',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
