# Generated by Django 4.2.7 on 2023-12-18 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_transfer_delete_credits_delete_debits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='receiver',
            new_name='receiver_account',
        ),
    ]
