# Generated by Django 4.2.7 on 2023-12-18 01:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_rename_receiver_transfer_receiver_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
